import type { Response } from 'express';
import { runPdfVectorizationJob } from '../jobs/pdfVectorization.job';
import { pdfService } from '../services/pdf.service';
import { ApiResponse } from '../utils/ApiResponse';
import { ApiError } from '../utils/ApiError';
import type { AuthRequest } from '../middleware/auth';

/**
 * PDF controller — thin HTTP layer over `pdfService`.
 * All persistence + parsing logic lives in the service / utility.
 */
export const pdfController = {
  upload: async (req: AuthRequest, res: Response): Promise<void> => {
    if (!req.file) {
      throw ApiError.badRequest('No PDF file provided. Use form field "file".');
    }

    // Extract the authenticated user ID
    const userId = req.user?.id;
    if (!userId) {
      throw ApiError.badRequest('User context is missing. Authentication required.');
    }

    const result = await pdfService.ingestUploadedFile(req.file);

    // 1. Grab the unique ID generated by Cloudinary
    const uniqueFileId = result.filename;

    // 2. Fix the AI Search: Save chunks to ChromaDB using the exact unique ID 
    // that the frontend will send in the `activeDocs` array.
    void runPdfVectorizationJob({
      storedPath: result.storedPath,
      source: uniqueFileId,
      chunkOptions: { userId },
    });

    // 3. Fix the UI: Format the response exactly how your React frontend expects it
    res.status(201).json(
      ApiResponse.success({
        filename: result.originalName,    // Clean display name for your Sidebar UI
        originalName: result.originalName,
        storedFilename: uniqueFileId,     // The ID used to filter search queries
        url: result.storedPath,           // The direct Cloudinary URL so the PDF actually renders
        size: result.sizeBytes
      })
    );
  },

  testChunking: async (req: AuthRequest, res: Response): Promise<void> => {
    const { text } = req.body;

    if (!text || typeof text !== 'string') {
      throw ApiError.badRequest('Valid text is required.');
    }

    const userId = req.user?.id || 'test-user-id';

    const { prepareText } = await import('../lib/ai/textCleaner');
    const { chunkText } = await import('../lib/ai/chunker');

    const cleanedText = prepareText(text);

    const chunks = chunkText(cleanedText, 'test.pdf', {
      chunkSize: 500,
      overlap: 100,
      userId,
    });

    res.status(200).json(
      ApiResponse.success({
        originalLength: text.length,
        totalChunks: chunks.length,
        preview: chunks.slice(0, 2).map((chunk) => ({
          chunkIndex: chunk.metadata.chunkIndex,
          text: chunk.text.slice(0, 200),
        })),
      }),
    );
  },
};